### ISSUE TITLE
Arbitrary attribute throws assertion error

### ISSUE THREAD

**Issue by ao-apps** [aoindustries/semanticcms-core-servlet#1]
https://aoindustries.com/oss/aoserv?navigation=true

`Caused by: java.lang.AssertionError: Expected com.aoapps.encoding.XhtmlAttributeWriter, got com.aoapps.encoding.TextWriter
        at com.aoapps.encoding.XhtmlAttributeWritable.writeTo(XhtmlAttributeWritable.java:43)
        at com.aoapps.encoding.WhitespaceWritable.writeTo(WhitespaceWritable.java:41)
        at com.aoapps.html.any.Attributes$Text.attribute(Attributes.java:447)
        at com.aoapps.html.any.attributes.text.Attribute.attribute(Attribute.java:57)
        at com.aoapps.html.any.attributes.text.Attribute.attribute(Attribute.java:87)
        at com.semanticcms.core.servlet.impl.NavigationTreeImpl.writeNode(NavigationTreeImpl.java:485)
        at com.semanticcms.core.servlet.impl.NavigationTreeImpl.writeNavigationTreeImpl(NavigationTreeImpl.java:389)
        at com.semanticcms.core.servlet.impl.NavigationTreeImpl.writeNavigationTreeImpl(NavigationTreeImpl.java:265)
        at com.semanticcms.core.taglib.NavigationTreeTag.doTag(NavigationTreeTag.java:114)`

**Comment by ao-apps** [comment]
Fixed bug in underlying API: https://github.com/ao-apps/ao-fluent-html-any/commit/55b6a10b7a7df273b5e2767f8ee10cc03d7b08fe
